CREATE TABLE country_master(
country_code NVARCHAR(3),
country_name NVARCHAR(50)
)

INSERT country_master(country_code, country_name) VALUES('AFG','Afghanistan')
INSERT country_master(country_code, country_name) VALUES('ALA','Aland Islands')
INSERT country_master(country_code, country_name) VALUES('ALB','Albania')
INSERT country_master(country_code, country_name) VALUES('DZA','Algeria')
INSERT country_master(country_code, country_name) VALUES('ASM','American Samoa')
INSERT country_master(country_code, country_name) VALUES('AND','Andorra')
INSERT country_master(country_code, country_name) VALUES('AGO','Angola')
INSERT country_master(country_code, country_name) VALUES('AIA','Anguilla')
INSERT country_master(country_code, country_name) VALUES('ATA','Antarctica')
INSERT country_master(country_code, country_name) VALUES('ATG','Antigua and Barbuda')
INSERT country_master(country_code, country_name) VALUES('ARG','Argentina')
INSERT country_master(country_code, country_name) VALUES('ARM','Armenia')
INSERT country_master(country_code, country_name) VALUES('ABW','Aruba')
INSERT country_master(country_code, country_name) VALUES('AUS','Australia')
INSERT country_master(country_code, country_name) VALUES('AUT','Austria')
INSERT country_master(country_code, country_name) VALUES('AZE','Azerbaijan')
INSERT country_master(country_code, country_name) VALUES('BHS','Bahamas')
INSERT country_master(country_code, country_name) VALUES('BHR','Bahrain')
INSERT country_master(country_code, country_name) VALUES('BGD','Bangladesh')
INSERT country_master(country_code, country_name) VALUES('BRB','Barbados')
INSERT country_master(country_code, country_name) VALUES('BLR','Belarus')
INSERT country_master(country_code, country_name) VALUES('BEL','Belgium')
INSERT country_master(country_code, country_name) VALUES('BLZ','Belize')
INSERT country_master(country_code, country_name) VALUES('BEN','Benin')
INSERT country_master(country_code, country_name) VALUES('BMU','Bermuda')
INSERT country_master(country_code, country_name) VALUES('BTN','Bhutan')
INSERT country_master(country_code, country_name) VALUES('BOL','Bolivia')
INSERT country_master(country_code, country_name) VALUES('BIH','Bosnia and Herzegovina')
INSERT country_master(country_code, country_name) VALUES('BWA','Botswana')
INSERT country_master(country_code, country_name) VALUES('BVT','Bouvet Island')
INSERT country_master(country_code, country_name) VALUES('BRA','Brazil')
INSERT country_master(country_code, country_name) VALUES('VGB','British Virgin Islands')
INSERT country_master(country_code, country_name) VALUES('IOT','British Indian Ocean Territory')
INSERT country_master(country_code, country_name) VALUES('BRN','Brunei Darussalam')
INSERT country_master(country_code, country_name) VALUES('BGR','Bulgaria')
INSERT country_master(country_code, country_name) VALUES('BFA','Burkina Faso')
INSERT country_master(country_code, country_name) VALUES('BDI','Burundi')
INSERT country_master(country_code, country_name) VALUES('KHM','Cambodia')
INSERT country_master(country_code, country_name) VALUES('CMR','Cameroon')
INSERT country_master(country_code, country_name) VALUES('CAN','Canada')
INSERT country_master(country_code, country_name) VALUES('CPV','Cape Verde')
INSERT country_master(country_code, country_name) VALUES('CYM','Cayman Islands')
INSERT country_master(country_code, country_name) VALUES('CAF','Central African Republic')
INSERT country_master(country_code, country_name) VALUES('TCD','Chad')
INSERT country_master(country_code, country_name) VALUES('CHL','Chile')
INSERT country_master(country_code, country_name) VALUES('CHN','China')
INSERT country_master(country_code, country_name) VALUES('HKG','Hong Kong, SAR China')
INSERT country_master(country_code, country_name) VALUES('MAC','Macao, SAR China')
INSERT country_master(country_code, country_name) VALUES('CXR','Christmas Island')
INSERT country_master(country_code, country_name) VALUES('CCK','Cocos (Keeling) Islands')
INSERT country_master(country_code, country_name) VALUES('COL','Colombia')
INSERT country_master(country_code, country_name) VALUES('COM','Comoros')
INSERT country_master(country_code, country_name) VALUES('COG','Congo (Brazzaville)')
INSERT country_master(country_code, country_name) VALUES('COD','Congo, (Kinshasa)')
INSERT country_master(country_code, country_name) VALUES('COK','Cook Islands')
INSERT country_master(country_code, country_name) VALUES('CRI','Costa Rica')
INSERT country_master(country_code, country_name) VALUES('CIV','Côte dIvoire')
INSERT country_master(country_code, country_name) VALUES('HRV','Croatia')
INSERT country_master(country_code, country_name) VALUES('CUB','Cuba')
INSERT country_master(country_code, country_name) VALUES('CYP','Cyprus')
INSERT country_master(country_code, country_name) VALUES('CZE','Czech Republic')
INSERT country_master(country_code, country_name) VALUES('DNK','Denmark')
INSERT country_master(country_code, country_name) VALUES('DJI','Djibouti')
INSERT country_master(country_code, country_name) VALUES('DMA','Dominica')
INSERT country_master(country_code, country_name) VALUES('DOM','Dominican Republic')
INSERT country_master(country_code, country_name) VALUES('ECU','Ecuador')
INSERT country_master(country_code, country_name) VALUES('EGY','Egypt')
INSERT country_master(country_code, country_name) VALUES('SLV','El Salvador')
INSERT country_master(country_code, country_name) VALUES('GNQ','Equatorial Guinea')
INSERT country_master(country_code, country_name) VALUES('ERI','Eritrea')
INSERT country_master(country_code, country_name) VALUES('EST','Estonia')
INSERT country_master(country_code, country_name) VALUES('ETH','Ethiopia')
INSERT country_master(country_code, country_name) VALUES('FLK','Falkland Islands (Malvinas)')
INSERT country_master(country_code, country_name) VALUES('FRO','Faroe Islands')
INSERT country_master(country_code, country_name) VALUES('FJI','Fiji')
INSERT country_master(country_code, country_name) VALUES('FIN','Finland')
INSERT country_master(country_code, country_name) VALUES('FRA','France')
INSERT country_master(country_code, country_name) VALUES('GUF','French Guiana')
INSERT country_master(country_code, country_name) VALUES('PYF','French Polynesia')
INSERT country_master(country_code, country_name) VALUES('ATF','French Southern Territories')
INSERT country_master(country_code, country_name) VALUES('GAB','Gabon')
INSERT country_master(country_code, country_name) VALUES('GMB','Gambia')
INSERT country_master(country_code, country_name) VALUES('GEO','Georgia')
INSERT country_master(country_code, country_name) VALUES('DEU','Germany')
INSERT country_master(country_code, country_name) VALUES('GHA','Ghana')
INSERT country_master(country_code, country_name) VALUES('GIB','Gibraltar')
INSERT country_master(country_code, country_name) VALUES('GRC','Greece')
INSERT country_master(country_code, country_name) VALUES('GRL','Greenland')
INSERT country_master(country_code, country_name) VALUES('GRD','Grenada')
INSERT country_master(country_code, country_name) VALUES('GLP','Guadeloupe')
INSERT country_master(country_code, country_name) VALUES('GUM','Guam')
INSERT country_master(country_code, country_name) VALUES('GTM','Guatemala')
INSERT country_master(country_code, country_name) VALUES('GGY','Guernsey')
INSERT country_master(country_code, country_name) VALUES('GIN','Guinea')
INSERT country_master(country_code, country_name) VALUES('GNB','Guinea-Bissau')
INSERT country_master(country_code, country_name) VALUES('GUY','Guyana')
INSERT country_master(country_code, country_name) VALUES('HTI','Haiti')
INSERT country_master(country_code, country_name) VALUES('HMD','Heard and Mcdonald Islands')
INSERT country_master(country_code, country_name) VALUES('VAT','Holy See (Vatican City State)')
INSERT country_master(country_code, country_name) VALUES('HND','Honduras')
INSERT country_master(country_code, country_name) VALUES('HUN','Hungary')
INSERT country_master(country_code, country_name) VALUES('ISL','Iceland')
INSERT country_master(country_code, country_name) VALUES('IND','India')
INSERT country_master(country_code, country_name) VALUES('IDN','Indonesia')
INSERT country_master(country_code, country_name) VALUES('IRN','Iran, Islamic Republic of')
INSERT country_master(country_code, country_name) VALUES('IRQ','Iraq')
INSERT country_master(country_code, country_name) VALUES('IRL','Ireland')
INSERT country_master(country_code, country_name) VALUES('IMN','Isle of Man')
INSERT country_master(country_code, country_name) VALUES('ISR','Israel')
INSERT country_master(country_code, country_name) VALUES('ITA','Italy')
INSERT country_master(country_code, country_name) VALUES('JAM','Jamaica')
INSERT country_master(country_code, country_name) VALUES('JPN','Japan')
INSERT country_master(country_code, country_name) VALUES('JEY','Jersey')
INSERT country_master(country_code, country_name) VALUES('JOR','Jordan')
INSERT country_master(country_code, country_name) VALUES('KAZ','Kazakhstan')
INSERT country_master(country_code, country_name) VALUES('KEN','Kenya')
INSERT country_master(country_code, country_name) VALUES('KIR','Kiribati')
INSERT country_master(country_code, country_name) VALUES('PRK','Korea (North)')
INSERT country_master(country_code, country_name) VALUES('KOR','Korea (South)')
INSERT country_master(country_code, country_name) VALUES('KWT','Kuwait')
INSERT country_master(country_code, country_name) VALUES('KGZ','Kyrgyzstan')
INSERT country_master(country_code, country_name) VALUES('LAO','Lao PDR')
INSERT country_master(country_code, country_name) VALUES('LVA','Latvia')
INSERT country_master(country_code, country_name) VALUES('LBN','Lebanon')
INSERT country_master(country_code, country_name) VALUES('LSO','Lesotho')
INSERT country_master(country_code, country_name) VALUES('LBR','Liberia')
INSERT country_master(country_code, country_name) VALUES('LBY','Libya')
INSERT country_master(country_code, country_name) VALUES('LIE','Liechtenstein')
INSERT country_master(country_code, country_name) VALUES('LTU','Lithuania')
INSERT country_master(country_code, country_name) VALUES('LUX','Luxembourg')
INSERT country_master(country_code, country_name) VALUES('MKD','Macedonia, Republic of')
INSERT country_master(country_code, country_name) VALUES('MDG','Madagascar')
INSERT country_master(country_code, country_name) VALUES('MWI','Malawi')
INSERT country_master(country_code, country_name) VALUES('MYS','Malaysia')
INSERT country_master(country_code, country_name) VALUES('MDV','Maldives')
INSERT country_master(country_code, country_name) VALUES('MLI','Mali')
INSERT country_master(country_code, country_name) VALUES('MLT','Malta')
INSERT country_master(country_code, country_name) VALUES('MHL','Marshall Islands')
INSERT country_master(country_code, country_name) VALUES('MTQ','Martinique')
INSERT country_master(country_code, country_name) VALUES('MRT','Mauritania')
INSERT country_master(country_code, country_name) VALUES('MUS','Mauritius')
INSERT country_master(country_code, country_name) VALUES('MYT','Mayotte')
INSERT country_master(country_code, country_name) VALUES('MEX','Mexico')
INSERT country_master(country_code, country_name) VALUES('FSM','Micronesia, Federated States of')
INSERT country_master(country_code, country_name) VALUES('MDA','Moldova')
INSERT country_master(country_code, country_name) VALUES('MCO','Monaco')
INSERT country_master(country_code, country_name) VALUES('MNG','Mongolia')
INSERT country_master(country_code, country_name) VALUES('MNE','Montenegro')
INSERT country_master(country_code, country_name) VALUES('MSR','Montserrat')
INSERT country_master(country_code, country_name) VALUES('MAR','Morocco')
INSERT country_master(country_code, country_name) VALUES('MOZ','Mozambique')
INSERT country_master(country_code, country_name) VALUES('MMR','Myanmar')
INSERT country_master(country_code, country_name) VALUES('NAM','Namibia')
INSERT country_master(country_code, country_name) VALUES('NRU','Nauru')
INSERT country_master(country_code, country_name) VALUES('NPL','Nepal')
INSERT country_master(country_code, country_name) VALUES('NLD','Netherlands')
INSERT country_master(country_code, country_name) VALUES('ANT','Netherlands Antilles')
INSERT country_master(country_code, country_name) VALUES('NCL','New Caledonia')
INSERT country_master(country_code, country_name) VALUES('NZL','New Zealand')
INSERT country_master(country_code, country_name) VALUES('NIC','Nicaragua')
INSERT country_master(country_code, country_name) VALUES('NER','Niger')
INSERT country_master(country_code, country_name) VALUES('NGA','Nigeria')
INSERT country_master(country_code, country_name) VALUES('NIU','Niue')
INSERT country_master(country_code, country_name) VALUES('NFK','Norfolk Island')
INSERT country_master(country_code, country_name) VALUES('MNP','Northern Mariana Islands')
INSERT country_master(country_code, country_name) VALUES('NOR','Norway')
INSERT country_master(country_code, country_name) VALUES('OMN','Oman')
INSERT country_master(country_code, country_name) VALUES('PAK','Pakistan')
INSERT country_master(country_code, country_name) VALUES('PLW','Palau')
INSERT country_master(country_code, country_name) VALUES('PSE','Palestinian Territory')
INSERT country_master(country_code, country_name) VALUES('PAN','Panama')
INSERT country_master(country_code, country_name) VALUES('PNG','Papua New Guinea')
INSERT country_master(country_code, country_name) VALUES('PRY','Paraguay')
INSERT country_master(country_code, country_name) VALUES('PER','Peru')
INSERT country_master(country_code, country_name) VALUES('PHL','Philippines')
INSERT country_master(country_code, country_name) VALUES('PCN','Pitcairn')
INSERT country_master(country_code, country_name) VALUES('POL','Poland')
INSERT country_master(country_code, country_name) VALUES('PRT','Portugal')
INSERT country_master(country_code, country_name) VALUES('PRI','Puerto Rico')
INSERT country_master(country_code, country_name) VALUES('QAT','Qatar')
INSERT country_master(country_code, country_name) VALUES('REU','Réunion')
INSERT country_master(country_code, country_name) VALUES('ROU','Romania')
INSERT country_master(country_code, country_name) VALUES('RUS','Russian Federation')
INSERT country_master(country_code, country_name) VALUES('RWA','Rwanda')
INSERT country_master(country_code, country_name) VALUES('BLM','Saint-Barthélemy')
INSERT country_master(country_code, country_name) VALUES('SHN','Saint Helena')
INSERT country_master(country_code, country_name) VALUES('KNA','Saint Kitts and Nevis')
INSERT country_master(country_code, country_name) VALUES('LCA','Saint Lucia')
INSERT country_master(country_code, country_name) VALUES('MAF','Saint-Martin (French part)')
INSERT country_master(country_code, country_name) VALUES('SPM','Saint Pierre and Miquelon')
INSERT country_master(country_code, country_name) VALUES('VCT','Saint Vincent and Grenadines')
INSERT country_master(country_code, country_name) VALUES('WSM','Samoa')
INSERT country_master(country_code, country_name) VALUES('SMR','San Marino')
INSERT country_master(country_code, country_name) VALUES('STP','Sao Tome and Principe')
INSERT country_master(country_code, country_name) VALUES('SAU','Saudi Arabia')
INSERT country_master(country_code, country_name) VALUES('SEN','Senegal')
INSERT country_master(country_code, country_name) VALUES('SRB','Serbia')
INSERT country_master(country_code, country_name) VALUES('SYC','Seychelles')
INSERT country_master(country_code, country_name) VALUES('SLE','Sierra Leone')
INSERT country_master(country_code, country_name) VALUES('SGP','Singapore')
INSERT country_master(country_code, country_name) VALUES('SVK','Slovakia')
INSERT country_master(country_code, country_name) VALUES('SVN','Slovenia')
INSERT country_master(country_code, country_name) VALUES('SLB','Solomon Islands')
INSERT country_master(country_code, country_name) VALUES('SOM','Somalia')
INSERT country_master(country_code, country_name) VALUES('ZAF','South Africa')
INSERT country_master(country_code, country_name) VALUES('SGS','South Georgia and the South Sandwich Islands')
INSERT country_master(country_code, country_name) VALUES('SSD','South Sudan')
INSERT country_master(country_code, country_name) VALUES('ESP','Spain')
INSERT country_master(country_code, country_name) VALUES('LKA','Sri Lanka')
INSERT country_master(country_code, country_name) VALUES('SDN','Sudan')
INSERT country_master(country_code, country_name) VALUES('SUR','Suriname')
INSERT country_master(country_code, country_name) VALUES('SJM','Svalbard and Jan Mayen Islands')
INSERT country_master(country_code, country_name) VALUES('SWZ','Swaziland')
INSERT country_master(country_code, country_name) VALUES('SWE','Sweden')
INSERT country_master(country_code, country_name) VALUES('CHE','Switzerland')
INSERT country_master(country_code, country_name) VALUES('SYR','Syrian Arab Republic (Syria)')
INSERT country_master(country_code, country_name) VALUES('TWN','Taiwan, Republic of China')
INSERT country_master(country_code, country_name) VALUES('TJK','Tajikistan')
INSERT country_master(country_code, country_name) VALUES('TZA','Tanzania, United Republic of')
INSERT country_master(country_code, country_name) VALUES('THA','Thailand')
INSERT country_master(country_code, country_name) VALUES('TLS','Timor-Leste')
INSERT country_master(country_code, country_name) VALUES('TGO','Togo')
INSERT country_master(country_code, country_name) VALUES('TKL','Tokelau')
INSERT country_master(country_code, country_name) VALUES('TON','Tonga')
INSERT country_master(country_code, country_name) VALUES('TTO','Trinidad and Tobago')
INSERT country_master(country_code, country_name) VALUES('TUN','Tunisia')
INSERT country_master(country_code, country_name) VALUES('TUR','Turkey')
INSERT country_master(country_code, country_name) VALUES('TKM','Turkmenistan')
INSERT country_master(country_code, country_name) VALUES('TCA','Turks and Caicos Islands')
INSERT country_master(country_code, country_name) VALUES('TUV','Tuvalu')
INSERT country_master(country_code, country_name) VALUES('UGA','Uganda')
INSERT country_master(country_code, country_name) VALUES('UKR','Ukraine')
INSERT country_master(country_code, country_name) VALUES('ARE','United Arab Emirates')
INSERT country_master(country_code, country_name) VALUES('GBR','United Kingdom')
INSERT country_master(country_code, country_name) VALUES('USA','United States of America')
INSERT country_master(country_code, country_name) VALUES('UMI','US Minor Outlying Islands')
INSERT country_master(country_code, country_name) VALUES('URY','Uruguay')
INSERT country_master(country_code, country_name) VALUES('UZB','Uzbekistan')
INSERT country_master(country_code, country_name) VALUES('VUT','Vanuatu')
INSERT country_master(country_code, country_name) VALUES('VEN','Venezuela (Bolivarian Republic)')
INSERT country_master(country_code, country_name) VALUES('VNM','Viet Nam')
INSERT country_master(country_code, country_name) VALUES('VIR','Virgin Islands, US')
INSERT country_master(country_code, country_name) VALUES('WLF','Wallis and Futuna Islands')
INSERT country_master(country_code, country_name) VALUES('ESH','Western Sahara')
INSERT country_master(country_code, country_name) VALUES('YEM','Yemen')
INSERT country_master(country_code, country_name) VALUES('ZMB','Zambia')
INSERT country_master(country_code, country_name) VALUES('ZWE','Zimbabwe')
